
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Loredana
 */
public class Actualizare extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con = null;
    String titluInterfata;

    /**
     * Creates new form ActualizarePersoana
     */
    public Actualizare() {
        initComponents();
        con = ConexiuneBD.conect();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTitluCautat = new javax.swing.JTextField();
        cautare = new javax.swing.JButton();
        revenire = new javax.swing.JButton();
        revenire1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfTitlu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tftNrPag = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPret = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti titlul carti");

        cautare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare.setForeground(new java.awt.Color(102, 0, 51));
        cautare.setText("Cautare");
        cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareActionPerformed(evt);
            }
        });

        revenire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        revenire.setForeground(new java.awt.Color(102, 0, 51));
        revenire.setText("Revenire");
        revenire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenireActionPerformed(evt);
            }
        });

        revenire1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        revenire1.setForeground(new java.awt.Color(102, 0, 51));
        revenire1.setText("Actualizare date");
        revenire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenire1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Titlu");

        jLabel2.setText("Autor");

        jLabel3.setText("Nr pagini");

        jLabel4.setText("Pret");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(revenire1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(revenire)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(67, 67, 67)
                        .addComponent(tfPret, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67)
                        .addComponent(tftNrPag, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(67, 67, 67)
                            .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jLabel1)
                    .addGap(27, 27, 27)
                    .addComponent(tfTitluCautat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(328, 328, 328)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tftNrPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revenire)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revenire1)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(tfTitluCautat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautareActionPerformed
        titluInterfata = tfTitluCautat.getText();
        String sql = "SELECT * FROM `carti` where `Titlu`='" + titluInterfata + "'";
        try {
            pst = con.prepareStatement(sql);
            ResultSet rezultat = pst.executeQuery(sql);
            int j = 0;
            while (rezultat.next()) {
                String titlu = rezultat.getString("Titlu");
                tfTitlu.setText(titlu);
                String autor = rezultat.getString("Autor");
                tfAutor.setText(autor);
                int nrpag = rezultat.getInt("NrPag");
                tftNrPag.setText(Integer.toString(nrpag));
                double pret = rezultat.getDouble("Pret");
                tfPret.setText(Double.toString(pret));
                j++;

            }
            if (j == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");

            }

        } catch (SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }
    }//GEN-LAST:event_cautareActionPerformed

    private void revenireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenireActionPerformed

        setVisible(false);
    }//GEN-LAST:event_revenireActionPerformed

    private void revenire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenire1ActionPerformed
        boolean corect = true;
        String titlu = "";
        String autor = "";
        int nrpag = 0;
        double pret = 0.0;
        try {
            titluInterfata = tfTitluCautat.getText();
            titlu = tfTitlu.getText();
            autor = tfAutor.getText();
            nrpag = Integer.valueOf(tftNrPag.getText());
            pret = Double.valueOf(tfPret.getText());
        } catch (Exception e) {
            corect = false;
            JOptionPane.showMessageDialog(rootPane, "Verificati datele introduse", "Eroare", JOptionPane.ERROR_MESSAGE);
        }

        if (corect && !titlu.isEmpty()) {

            String sql1 = "UPDATE `carti`  SET Titlu='" + titlu + "',Autor='" + autor + "',NrPag='" + nrpag + "',Pret='" + pret + "' WHERE Titlu='" + titluInterfata + "'";
            try {
                PreparedStatement pst = con.prepareStatement(sql1);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(rootPane, "Actualizare efectuata");
                tfTitlu.setText("");
                tfAutor.setText("");
                tftNrPag.setText("");
                tfPret.setText("");
                this.setVisible(false);

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_revenire1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cautare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton revenire;
    private javax.swing.JButton revenire1;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfPret;
    private javax.swing.JTextField tfTitlu;
    private javax.swing.JTextField tfTitluCautat;
    private javax.swing.JTextField tftNrPag;
    // End of variables declaration//GEN-END:variables
}
