
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Loredana
 */
public class ActualizareCombo extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con = null;
    String titluPreluatCombo;
    Statement stare;
    Vector v;

    /**
     * Creates new form ActualizarePersoana
     */
    public ActualizareCombo() {
        initComponents();
        con = ConexiuneBD.conect();
        setLocationRelativeTo(null);
        v = new Vector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfSubtitlu = new javax.swing.JTextField();
        revenire = new javax.swing.JButton();
        actualizare = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfTitlu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNrPag = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPret = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbCarti = new javax.swing.JComboBox<>();
        cautare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti parte din titlu");

        revenire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        revenire.setForeground(new java.awt.Color(102, 0, 51));
        revenire.setText("Revenire");
        revenire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenireActionPerformed(evt);
            }
        });

        actualizare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        actualizare.setForeground(new java.awt.Color(102, 0, 51));
        actualizare.setText("Actualizare date");
        actualizare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizareActionPerformed(evt);
            }
        });

        jLabel6.setText("Titlu");

        jLabel2.setText("Autor");

        jLabel3.setText("Nr pagini");

        jLabel4.setText("Pret");

        jLabel5.setText("Carti gasite");

        cbCarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCartiActionPerformed(evt);
            }
        });

        cautare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare.setForeground(new java.awt.Color(102, 0, 51));
        cautare.setText("Cautare");
        cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(actualizare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(revenire)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(257, 257, 257)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(67, 67, 67)
                                    .addComponent(tfPret, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(67, 67, 67)
                                    .addComponent(tfNrPag, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(67, 67, 67)
                                        .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(jLabel5)
                            .addGap(27, 27, 27)
                            .addComponent(cbCarti, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jLabel1)
                    .addGap(27, 27, 27)
                    .addComponent(tfSubtitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCarti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNrPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revenire)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(actualizare)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfSubtitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(403, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revenireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenireActionPerformed

        setVisible(false);
    }//GEN-LAST:event_revenireActionPerformed

    private void actualizareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizareActionPerformed
        boolean corect = true;
        String titluNou = "";
        String autor = "";
        int nrpag = 0;
        double pret = 0.0;
        try {

            titluNou = tfTitlu.getText();
            autor = tfAutor.getText();
            nrpag = Integer.valueOf(tfNrPag.getText());
            pret = Double.valueOf(tfPret.getText());
        } catch (Exception e) {
            corect = false;
            JOptionPane.showMessageDialog(rootPane, "Verificati datele introduse", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        if (corect && !titluNou.isEmpty()) {

            String sql1 = "UPDATE `carti`  SET Titlu='" + titluNou + "',Autor='" + autor + "',NrPag='" + nrpag + "',Pret='" + pret + "' WHERE Titlu='" + titluPreluatCombo + "'";
            try {
                PreparedStatement pst = con.prepareStatement(sql1);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Actualizare efectuata");
                tfTitlu.setText("");
                tfAutor.setText("");
                tfNrPag.setText("");
                tfPret.setText("");
                this.setVisible(false);

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizareActionPerformed

    private void cautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautareActionPerformed
        tfTitlu.setText("");
        tfAutor.setText("");
        tfNrPag.setText("");
        tfPret.setText("");
        cbCarti.removeAllItems();
        v = new Vector();
        String titluInterfata = tfSubtitlu.getText();
        try {
            stare = con.createStatement();
            String intrebare = "SELECT * FROM `carti` where `Titlu` LIKE '%" + titluInterfata + "%'";
            ResultSet rezultat = stare.executeQuery(intrebare);
            int j = 0;
            while (rezultat.next()) {
                String titlu = rezultat.getString("Titlu");
                String autor = rezultat.getString("Autor");
                int nrpag = rezultat.getInt("NrPag");
                double pret = rezultat.getDouble("Pret");
                Carte c = new Carte(titlu, autor, nrpag, pret);
                v.add(c);
                cbCarti.addItem(c.afisare());
                j++;
            }
            if (j == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");
            }

        } catch (SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cautareActionPerformed

    private void cbCartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCartiActionPerformed
        if (cbCarti.getSelectedIndex() > -1) {
            Carte c = new Carte((Carte) v.elementAt(cbCarti.getSelectedIndex()));
            titluPreluatCombo = c.getTitlu();
            String sql = "SELECT * FROM `carti` where `Titlu`='" + titluPreluatCombo + "'";
            try {
                pst = con.prepareStatement(sql);
                ResultSet rezultat = pst.executeQuery(sql);
                int j = 0;
                while (rezultat.next()) {
                    String titlu = rezultat.getString("Titlu");
                    tfTitlu.setText(titlu);
                    String autor = rezultat.getString("Autor");
                    tfAutor.setText(autor);
                    int nrpag = rezultat.getInt("NrPag");
                    tfNrPag.setText(Integer.toString(nrpag));
                    double pret = rezultat.getDouble("Pret");
                    tfPret.setText(Double.toString(pret));
                    j++;
                }
                if (j == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");
                }

            } catch (SQLException sqle) {
                System.err.println("Eroare conectare: " + sqle);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbCartiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizareCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizare;
    private javax.swing.JButton cautare;
    private javax.swing.JComboBox<String> cbCarti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton revenire;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfNrPag;
    private javax.swing.JTextField tfPret;
    private javax.swing.JTextField tfSubtitlu;
    private javax.swing.JTextField tfTitlu;
    // End of variables declaration//GEN-END:variables
}
