
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Loredana
 */
public class Cautare extends javax.swing.JFrame {

    Statement stare;
    Connection con = null;

    /**
     * Creates new form Cautare
     */
    public Cautare() {
        initComponents();
        con = ConexiuneBD.conect();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cautare = new javax.swing.JButton();
        Revenire = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfTitlu = new javax.swing.JTextField();
        lista = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        tfSubtitlu = new javax.swing.JTextField();
        cautare1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cautare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare.setForeground(new java.awt.Color(102, 0, 51));
        cautare.setText("Cautare");
        cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareActionPerformed(evt);
            }
        });

        Revenire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Revenire.setForeground(new java.awt.Color(102, 0, 51));
        Revenire.setText("Revenire");
        Revenire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenireActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduceti titlul cartii");

        jLabel2.setText("Introduceti parte din titlu");

        cautare1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare1.setForeground(new java.awt.Color(102, 0, 51));
        cautare1.setText("Cautare");
        cautare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautare1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Revenire)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(tfSubtitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cautare1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(301, 301, 301))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cautare1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfSubtitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Revenire)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautareActionPerformed
        lista.removeAll();
        String titluInterfata = tfTitlu.getText();
        try {
            stare = con.createStatement();
            String intrebare = "SELECT * FROM `carti` where `Titlu`='" + titluInterfata + "'";

            ResultSet rezultat = stare.executeQuery(intrebare);
            int j = 0;
            while (rezultat.next()) {
                String titlu = rezultat.getString("Titlu");
                String autor = rezultat.getString("Autor");
                int nrpag = rezultat.getInt("NrPag");
                double pret = rezultat.getDouble("Pret");
                Carte c = new Carte(titlu, autor, nrpag, pret);
                lista.add(c.afisare());
                j++;
            }
            if (j == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");
            }

        } catch (SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }
    }//GEN-LAST:event_cautareActionPerformed

    private void RevenireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenireActionPerformed

        setVisible(false);
    }//GEN-LAST:event_RevenireActionPerformed

    private void cautare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautare1ActionPerformed
        lista.removeAll();
        String titluInterfata = tfSubtitlu.getText();
        try {
            stare = con.createStatement();
            String intrebare = "SELECT * FROM `carti` where `Titlu` LIKE '%" + titluInterfata + "%'";
            ResultSet rezultat = stare.executeQuery(intrebare);
            int j = 0;
            while (rezultat.next()) {
                String titlu = rezultat.getString("Titlu");
                String autor = rezultat.getString("Autor");
                int nrpag = rezultat.getInt("NrPag");
                double pret = rezultat.getDouble("Pret");
                Carte c = new Carte(titlu, autor, nrpag, pret);
                lista.add(c.afisare());
                j++;
            }
            if (j == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");
            }

        } catch (SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cautare1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cautare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cautare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Revenire;
    private javax.swing.JButton cautare;
    private javax.swing.JButton cautare1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.List lista;
    private javax.swing.JTextField tfSubtitlu;
    private javax.swing.JTextField tfTitlu;
    // End of variables declaration//GEN-END:variables
}
