
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Loredana
 */
public class Stergere extends javax.swing.JFrame {

    Statement stare;
    Connection con = null;
    String titluInterfata;
    Vector v;

    /**
     * Creates new form Stergere
     */
    public Stergere() {
        initComponents();
        con = ConexiuneBD.conect();
        v = new Vector();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTitlu = new javax.swing.JTextField();
        cautare = new javax.swing.JButton();
        Revenire = new javax.swing.JButton();
        Stergere = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduceti titlul cartii");

        cautare.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cautare.setForeground(new java.awt.Color(102, 0, 51));
        cautare.setText("Cautare");
        cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareActionPerformed(evt);
            }
        });

        Revenire.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Revenire.setForeground(new java.awt.Color(102, 0, 51));
        Revenire.setText("Revenire");
        Revenire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenireActionPerformed(evt);
            }
        });

        Stergere.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Stergere.setForeground(new java.awt.Color(102, 0, 51));
        Stergere.setText("Ştergere carte");
        Stergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(Stergere, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Revenire)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cautare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Revenire)
                    .addComponent(Stergere))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautareActionPerformed
        titluInterfata = tfTitlu.getText();
        try {
            stare = con.createStatement();
            String intrebare = "SELECT * FROM `carti` where `Titlu`='" + titluInterfata + "'";

            ResultSet rezultat = stare.executeQuery(intrebare);
            int j = 0;
            while (rezultat.next()) {
                String titlu = rezultat.getString("Titlu");
                String autor = rezultat.getString("Autor");
                int nrpag = rezultat.getInt("NrPag");
                double pret = rezultat.getDouble("Pret");
                Carte c = new Carte(titlu, autor, nrpag, pret);
                v.addElement(c.afisare());
                lista.setListData(v);
                j++;
            }
            if (j == 0) {
                JOptionPane.showMessageDialog(rootPane, "Cartea cautata nu exista in BD");
            }

        } catch (SQLException sqle) {
            System.err.println("Eroare conectare: " + sqle);
        }
    }//GEN-LAST:event_cautareActionPerformed

    private void RevenireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenireActionPerformed

        setVisible(false);
    }//GEN-LAST:event_RevenireActionPerformed

    private void StergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StergereActionPerformed

        if (lista.getSelectedIndex() > -1) {
            try {
                stare = con.createStatement();
                String sterg = "DELETE from `carti` where `Titlu` like '" + titluInterfata + "'";
                stare.executeUpdate(sterg);
                JOptionPane.showMessageDialog(this, "Stergere efectuata cu succes", "EROARE", JOptionPane.ERROR_MESSAGE);
                //se reinitializeaza tabelul
                v = new Vector();
                lista.setListData(v);
                stare.close();
            } catch (SQLException sqle) {
                System.err.println("Eroare conectare: " + sqle);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nu s-a selectat nicio inregistrare", "EROARE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_StergereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stergere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stergere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stergere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stergere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stergere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Revenire;
    private javax.swing.JButton Stergere;
    private javax.swing.JButton cautare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField tfTitlu;
    // End of variables declaration//GEN-END:variables
}
