
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Principala.java
 *
 * Created on Dec 11, 2011, 6:10:35 PM
 */
/**
 *
 * @author Loredana
 */
public class Principala extends javax.swing.JFrame {

    String d, a;
    int pag, n = 0;
    double pret;
    Vector v1, v2;
    LinkedList L1;
    boolean egal;
    Carte c;

    /**
     * Creates new form Principala
     */
    public Principala() {
        v1 = new Vector();
        v2 = new Vector();
        L1 = new LinkedList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl2 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setText("Denumire");

        jLabel2.setText("Autor");

        jLabel3.setText("Nr pagini");

        jLabel4.setText("Pret");

        b1.setText("Adaugare carte");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.setText("Citire din fisier si afisare in liste");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                            .addComponent(b1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(b3)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(b1)
                .addGap(18, 18, 18)
                .addComponent(b3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jl1);

        jScrollPane2.setViewportView(jl2);

        jLabel5.setText("Lista cartilor introduse");

        jLabel6.setText("Lista cartilor cu nr de pagini>100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

        d = t1.getText();
        a = t2.getText();
        char c1, c2;
        boolean corect = true;
        if (corect) {
            for (int i = 0; i < d.length(); i++) {
                c1 = d.charAt(i);
                if (c1 == '0' || c1 == '1' || c1 == '2' || c1 == '3' || c1 == '4' || c1 == '5' || c1 == '6' || c1 == '7' || c1 == '8' || c1 == '9') {
                    corect = false;
                }
            }
        }
        if (corect) {
            for (int i = 0; i < a.length(); i++) {
                c2 = a.charAt(i);
                if (c2 == '0' || c2 == '1' || c2 == '2' || c2 == '3' || c2 == '4' || c2 == '5' || c2 == '6' || c2 == '7' || c2 == '8' || c2 == '9') {
                    corect = false;
                }
            }
        }
        if (corect) {
            try {
                pag = Integer.valueOf(t3.getText());
            } catch (Exception e) {
                System.out.print(e);
                corect = false;
            }
        }
        if (corect) {

            try {
                pret = Double.valueOf(t4.getText());
            } catch (Exception e) {
                System.out.print(e);
                corect = false;
            }
        }
        if (pag <= 0 || pret <= 0) {
            corect = false;
        }
        if (corect) {
            c = new Carte(d, a, pag, pret);
            v1 = new Vector();
            v2 = new Vector();
            L1 = new LinkedList();
            try {
                /* instantierea unui obiect de tip "FileInputStream" ce va permite citirea
                    * din fisierul al carui nume este dat de parametru constructorului */

                FileInputStream f = new FileInputStream("carte.dat");
                /* instantierea unui stream de intrare auxiliar prin intermediul caruia
                    * se va realiza citirea din fisier */
                ObjectInputStream s = new ObjectInputStream(f);
                // se memoreaza continutul din stream-ul de intrare in containerul generic
                L1 = (LinkedList) s.readObject();

                // se inchide stream-ul de intrare
                s.close();
            } catch (IOException e1) {
                JOptionPane.showMessageDialog(this, e1.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
            }
            // se obtine obiectul de tip "Carte" din container ce corespunde cartii anterior selectate

            egal = false;
            for (int i = 0; i < L1.size(); i++) {
                // se acceseaza obiectul curent, convertindu-se spre tipul "Carte"
                Carte carte = (Carte) L1.get(i);
                if (carte.identica(c)) egal=true;
            }
            if (egal == false) {
                L1.add(c);

                try {
                    /* instantierea unui obiect de tip "FileOutputStream" ce va permite scrierea
                    * in fisierul al carui nume este dat de parametru constructorului */
                    FileOutputStream f = new FileOutputStream("carte.dat");
                    /* instantierea unui stream de iesire auxiliar prin intermediul caruia
                    * se va realiza scrierea in fisier */
                    ObjectOutputStream s = new ObjectOutputStream(f);
                    // se reinitializeaza continutul stream-ului de iesire
                    s.flush();
                    // se adauga continutul containerului generic la stream-ul de iesire
                    s.writeObject(L1);
                    // se inchide stream-ul de iesire 
                    s.close();
                } catch (IOException e1) {
                    JOptionPane.showMessageDialog(this, e1.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
                }
                // se actualizeaza continutul componentei grafice de tip "List" 
                jl1.removeAll();
                jl2.removeAll();
                for (int i = 0; i < L1.size(); i++) {
                    Carte carte = (Carte) L1.get(i);
                    v1.add(carte.afisare());
                    if (carte.getNrpag() > 100) {
                        v2.add(carte.afisare());
                    }
                }
                jl1.setListData(v1);
                jl2.setListData(v2);
            } else {
                JOptionPane.showConfirmDialog(null, "Mai exista aceasta carte-Reintroduceti");
            }

            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Nu ati introdus corect datele");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        L1 = new LinkedList();

        try {
            /* instantierea unui obiect de tip "FileInputStream" ce va permite citirea
                * din fisierul al carui nume este dat de parametru constructorului */
            FileInputStream f = new FileInputStream("carte.dat");
            /* instantierea unui stream de intrare auxiliar prin intermediul caruia
               * se va realiza citirea din fisier */
            ObjectInputStream s = new ObjectInputStream(f);
            // se memoreaza continutul din stream-ul de intrare in containerul generic
            L1 = (LinkedList) s.readObject();
            // se inchide stream-ul de intrare
            s.close();
        } catch (IOException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "EROARE", JOptionPane.ERROR_MESSAGE);
        }

        // se sterg toate informatile memorate in componenta grafica de tip "JList"
        jl1.removeAll();
        jl2.removeAll();
        // se sterg toate informatile memorate in containerul "Vector"
        v1 = new Vector();
        v2 = new Vector();

        // se parcurge containerul generic
        for (int i = 0; i < L1.size(); i++) {
            // se acceseaza obiectul curent, convertindu-se spre tipul "Carte"
            c = (Carte) L1.get(i);
            // conversia spre tipul "String" a obiectului de tip "Carte" se adauga la colectia "Vector"

            v1.add(c.afisare());
            if (c.getNrpag() > 100) {
                v2.add(c.afisare());
            }

        }
        // se adauga informatiile in listele de pe interfata grafica de tip "JList"
        jl1.setListData(v1);
        jl2.setListData(v2);
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList jl1;
    private javax.swing.JList jl2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables

}
