
import java.awt.CheckboxGroup;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lore
 */
public class ExCheckbox extends javax.swing.JFrame {

    /**
     * Creates new form ExCheckbox
     */
    public ExCheckbox() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cb1 = new java.awt.Checkbox();
        cb2 = new java.awt.Checkbox();
        cb3 = new java.awt.Checkbox();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        label = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb1.setLabel("unu");
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });

        cb2.setLabel("doi");
        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });

        cb3.setLabel("trei");
        cb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb3ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rb1);
        rb1.setText("patru");
        rb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("cinci");
        rb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rb3);
        rb3.setText("sase");
        rb3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb3ItemStateChanged(evt);
            }
        });

        label.setText("Exemplu Checkbox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb3)
                            .addComponent(rb1)
                            .addComponent(rb2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);
// TODO add your handling code here:
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
 String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);  // TODO add your handling code here:
    }//GEN-LAST:event_cb2ItemStateChanged

    private void cb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb3ItemStateChanged
   String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);     // TODO add your handling code here:
    }//GEN-LAST:event_cb3ItemStateChanged

    private void rb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb1ItemStateChanged
   String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);   // TODO add your handling code here:
    }//GEN-LAST:event_rb1ItemStateChanged

    private void rb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb2ItemStateChanged
    String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);    // TODO add your handling code here:
    }//GEN-LAST:event_rb2ItemStateChanged

    private void rb3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb3ItemStateChanged
String text="";
if(cb1.getState())text=text+cb1.getLabel()+" ";
if(cb2.getState())text=text+cb2.getLabel()+" ";
if(cb3.getState())text=text+cb3.getLabel()+" ";
if(rb1.isSelected())text=text+rb1.getText()+" ";
if(rb2.isSelected())text=text+rb2.getText()+" ";
if(rb3.isSelected())text=text+rb3.getText()+" ";
label.setText(text);   // TODO add your handling code here:
    }//GEN-LAST:event_rb3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExCheckbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExCheckbox().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Checkbox cb1;
    private java.awt.Checkbox cb2;
    private java.awt.Checkbox cb3;
    private java.awt.Label label;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    // End of variables declaration//GEN-END:variables
CheckboxGroup group = new CheckboxGroup();
}
